version: '3'

services:
  db:
    container_name: db
    image: postgres:14.5
    volumes:
      - ./.data/db:/var/lib/postgresql/data
    ports:
      - "15432:5432"
    environment:
      - POSTGRES_DB=code_challenge_req90791
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password

  frontend:
    container_name: frontend
    build: ./frontend
    volumes:
      - ./frontend/:/app
      # preserve node_modules folder in the container
      - /app/node_modules
    ports:
      - "8080:80"

  backend:
    container_name: backend
    build: ./backend
    volumes:
      - ./backend:/code
    ports:
      - "8081:80"
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_NAME=code_challenge_req90791
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
      - DEBUG=True
      - ALLOWED_HOSTS=localhost
      - CORS_ALLOWED_ORIGINS=http://localhost:8080
      - SECRET_KEY='django-insecure-hgnk_w#2j!sd$$3vapnfm6)a=pz9gdqr%cz@qvow$$l5=85jllh4'
    depends_on:
      - db