# Generated by Django 4.1.1 on 2022-09-18 02:39

from django.db import migrations, models
import django.db.models.deletion
import echocatch_tours_kanban.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Boat',
            fields=[
                ('id', models.CharField(default=echocatch_tours_kanban.models.short_uuid, max_length=22, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'boat',
                'ordering': ['swimlane__position', 'position'],
            },
        ),
        migrations.CreateModel(
            name='Swimlane',
            fields=[
                ('id', models.CharField(default=echocatch_tours_kanban.models.short_uuid, max_length=22, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'swimlane',
                'ordering': ['position'],
            },
        ),
        migrations.AddIndex(
            model_name='swimlane',
            index=models.Index(fields=['position'], name='swimlane_positio_1efa52_idx'),
        ),
        migrations.AddField(
            model_name='boat',
            name='swimlane',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boats', to='echocatch_tours_kanban.swimlane'),
        ),
        migrations.AddIndex(
            model_name='boat',
            index=models.Index(fields=['position'], name='boat_positio_a80051_idx'),
        ),
    ]
